# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhihu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zhihumember',
            name='avatar_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='头像'),
        ),
    ]
