# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhihu', '0002_auto_20170928_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zhihumember',
            name='zhihu_id',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='知乎ID'),
        ),
    ]
