# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhihu', '0003_auto_20170928_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zhihumember',
            name='url_token',
            field=models.CharField(max_length=255, unique=True, verbose_name='用户URL'),
        ),
    ]
